### ISSUE TITLE
[Bug - report] report UI

### ISSUE THREAD

**Issue by 0xMaero** [ninjadotorg/handshake-protocol#23]
![report_ui](https://user-images.githubusercontent.com/41943165/44019868-41d1e2c6-9f0a-11e8-8e69-e96e09b93d22.png)

**Comment by 0xhakawai** [comment]
- Select Match -> Select Event => done
- No event redirect to /pex => NO FIX (it's not important)
- remove id from outcomes => done
- Dropdown icon on middle page => NO SEE
- remove id from events => CAN'T fix
